Cloudflare Workers + Supabase: Replace Pool with Client
drizzle-team/drizzle-orm-docs pull request #103
Opened 2023-09-12 09:46 UTC by MonsterDeveloper

Current docs recommend using `pg`s `Pool` when working with Cloudflare Workers. Yet Workers are supposed to delegate pooling to tools like PgBouncer instead of handling it themselves.

The [official Postgres docs from Cloudflare](https://developers.cloudflare.com/workers/databases/connect-to-postgres/) recommend using `Client` as well.

This PR replaces `Pool` with `Client` in the Workers section of Supabase docs.

2023-09-20 07:36 UTC, AlexBlokh requested changes
Lets add a link to their official docs? I think the more information we provide - the better, wdyt?

2023-09-20 08:35 UTC, MonsterDeveloper commented
@AlexBlokh indeed:) Now that you’ve mentioned it, I’m thinking of moving this entire “Cloudflare” section to the Postgres page, since it is valid for any DB, not just Supabase. What do you think?

2023-09-20 09:58 UTC, AlexBlokh commented
yeah, does make total sense

2023-10-06 13:07 UTC, MonsterDeveloper commented
@AlexBlokh I'd really appreciate a review on this one:)

2024-01-08 12:09 UTC, vlad-stohnii commented
Thanks for your contribution! We have manually moved your changes to the new version of the site

2024-01-08 12:09 UTC, closed without merging